services:
    secit.json_ld:
        public: true
        class: SecIT\JsonLdBundle\Service\JsonLd

    secit.json_ld.twig_extension:
        class: SecIT\JsonLdBundle\Twig\JsonLdExtension
        public: false
        arguments:
            $jsonLd: '@secit.json_ld'
        tags:
            - { name: twig.extension }
